// SPDX-License-Identifier: AGPL-3.0-or-later
// Auto-generated from include/items.h enum identifiers (debug menu labels).

static const char* s_handItemNames[169] = {
    "Empty Hand",
    "Monster Vial 1",
    "Monster Vial 2",
    "Monster Vial 3",
    "Shield Rod",
    "Leather Shield",
    "Knight Shield",
    "Iron Shield",
    "Axelord Shield",
    "Herald Shield",
    "Dark Shield",
    "Goddess Shield",
    "Shaman Shield",
    "Medusa Shield",
    "Skull Shield",
    "Fire Shield",
    "Alucard Shield",
    "Sword of Dawn",
    "Basilard",
    "Short Sword",
    "Combat Knife",
    "Nunchaku",
    "Were Bane",
    "Rapier",
    "Karma Coin",
    "Magic Missile",
    "Red Rust",
    "Takemitsu",
    "Shotel",
    "Orange",
    "Apple",
    "Banana",
    "Grapes",
    "Strawberry",
    "Pineapple",
    "Peanuts",
    "Toadstool",
    "Shiitake",
    "Cheesecake",
    "Shortcake",
    "Tart",
    "Parfait",
    "Pudding",
    "Ice Cream",
    "Frankfurter",
    "Hamburger",
    "Pizza",
    "Cheese",
    "Ham And Eggs",
    "Omelette",
    "Morning Set",
    "Lunch A",
    "Lunch B",
    "Curry Rice",
    "Gyros Plate",
    "Spaghetti",
    "Grape Juice",
    "Barley Tea",
    "Green Tea",
    "Natou",
    "Ramen",
    "Miso Soup",
    "Sushi",
    "Pork Bun",
    "Red Bean Bun",
    "Chinese Bun",
    "Dim Sum Set",
    "Pot Roast",
    "Sirloin",
    "Turkey",
    "Meal Ticket",
    "Neutron Bomb",
    "Power of Sire",
    "Pentagram",
    "Bat Pentagram",
    "Shuriken",
    "Cross Shuriken",
    "Buffalo Star",
    "Flame Star",
    "Tnt",
    "Bwaka Knife",
    "Boomerang",
    "Javelin",
    "Tyrfing",
    "Namakura",
    "Knuckle Duster",
    "Gladius",
    "Scimitar",
    "Cutlass",
    "Saber",
    "Falchion",
    "Broadsword",
    "Bekatowa",
    "Damascus Sword",
    "Hunter Sword",
    "Estoc",
    "Bastard Sword",
    "Jewel Knuckles",
    "Claymore",
    "Talwar",
    "Katana",
    "Flamberge",
    "Iron Fist",
    "Zweihander",
    "Sword of Hador",
    "Luminus",
    "Harper",
    "Obsidian Sword",
    "Gram",
    "Jewel Sword",
    "Mormegil",
    "Firebrand",
    "Thunderbrand",
    "Icebrand",
    "Stone Sword",
    "Holy Sword",
    "Terminus Est",
    "Marsil",
    "Dark Blade",
    "Heaven Sword",
    "Fist of Tulkas",
    "Gurthang",
    "Mourneblade",
    "Alucard Sword",
    "Mablung Sword",
    "Badelaire",
    "Sword Familiar",
    "Great Sword",
    "Mace",
    "Morningstar",
    "Holy Rod",
    "Star Flail",
    "Moon Rod",
    "Chakram",
    "Fire Boomerang",
    "Iron Ball",
    "Holbein Dagger",
    "Blue Knuckles",
    "Dynamite",
    "Osafune Katana",
    "Masamune",
    "Muramasa",
    "Heart Refresh",
    "Runesword",
    "Antivenom",
    "Uncurse",
    "Life Apple",
    "Hammer",
    "Str Potion",
    "Luck Potion",
    "Smart Potion",
    "Attack Potion",
    "Shield Potion",
    "Resist Fire",
    "Resist Thunder",
    "Resist Ice",
    "Resist Stone",
    "Resist Holy",
    "Resist Dark",
    "Potion",
    "High Potion",
    "Elixir",
    "Manna Prism",
    "Vorpal Blade",
    "Crissaegrim",
    "Yasutsuna",
    "Library Card",
    "Alucart Shield",
    "Alucart Sword",
};

static const char* s_bodyItemNames[90] = {
    "No Armor",
    "Cloth Tunic",
    "Hide Cuirass",
    "Bronze Cuirass",
    "Iron Cuirass",
    "Steel Cuirass",
    "Silver Plate",
    "Gold Plate",
    "Platinum Mail",
    "Diamond Plate",
    "Fire Mail",
    "Lightning Mail",
    "Ice Mail",
    "Mirror Cuirass",
    "Spike Breaker",
    "Alucard Mail",
    "Dark Armor",
    "Healing Mail",
    "Holy Mail",
    "Walk Armor",
    "Brilliant Mail",
    "Mojo Mail",
    "Fury Plate",
    "Dracula Tunic",
    "Gods Garb",
    "Axe Lord Armor",
    "Empty Head",
    "Sunglasses",
    "Ballroom Mask",
    "Bandanna",
    "Felt Hat",
    "Velvet Hat",
    "Goggles",
    "Leather Hat",
    "Holy Glasses",
    "Steel Helm",
    "Stone Mask",
    "Circlet",
    "Gold Circlet",
    "Ruby Circlet",
    "Opal Circlet",
    "Topaz Circlet",
    "Beryl Circlet",
    "Cat Eye Circlet",
    "Coral Circlet",
    "Dragon Helm",
    "Silver Crown",
    "Wizard Hat",
    "No Cape",
    "Cloth Cape",
    "Reverse Cloak",
    "Elven Cloak",
    "Crystal Cloak",
    "Royal Cloak",
    "Blood Cloak",
    "Josephs Cloak",
    "Twilight Cloak",
    "No Accessory",
    "Moonstone",
    "Sunstone",
    "Bloodstone",
    "Staurolite",
    "Ring of Pales",
    "Zircon",
    "Aquamarine",
    "Turquoise",
    "Onyx",
    "Garnet",
    "Opal",
    "Diamond",
    "Lapis Lazuli",
    "Ring of Ares",
    "Gold Ring",
    "Silver Ring",
    "Ring of Varda",
    "Ring of Arcana",
    "Mystic Pendant",
    "Heart Broach",
    "Necklace of J",
    "Gauntlet",
    "Ankh of Life",
    "Ring of Feanor",
    "Medal",
    "Talisman",
    "Duplicator",
    "Kings Stone",
    "Covenant Stone",
    "Nauglamir",
    "Secret Boots",
    "Alucart Mail",
};
